version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:8.9.3
    steps:
      - checkout
      - restore_cache:
          key: Shinku-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: Shinku-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
      - add_ssh_keys:
          fingerprints:
            - "e7:64:09:c2:4a:33:92:e6:d5:ee:ad:9a:f8:44:b7:77"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == 'master' ]; then
              bash .circleci/setup-heroku.sh
              git push -f heroku master
            fi
